#   METROC++: MErger TRees On C++, a scalable code for the computation of merger trees in cosmological simulations.
#   Copyright (C) Edoardo Carlesi 2018-2019
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

#   Makefile.config
#   System-specific compiler directives
#   Choose your system (or add your own):

#SYSTEM = "NERUDA"
#SYSTEM = "LAPTOP"
#SYSTEM = "BARBAGIANNI"
SYSTEM = "EREBOS"
#SYSTEM = "LEIBNIZ"

# Code options:

# If reading particles from the binary snapshot directly then allow to store more information (e.g. on X and V).
#OPT += -DPART_SNAPSHOT

# Print information (on all tasks) about memory allocation, communication and other boring stuff.
#OPT += -DVERBOSE

# Set the number of particle used at COMPILE TIME. This is necessary because this way Halo class has a well-defined size,
# making MPI communication easier
OPT += -DNPTYPES=2

# Enable Zoom Mode
OPT += -DZOOM



#=============================================================================#

ifeq ($(SYSTEM), "LAPTOP")
    CXX       =  mpic++
    LDLIBS    += -lmpi
endif

#=============================================================================#

ifeq ($(SYSTEM), "BARBAGIANNI")
    CXX       =  mpic++
    LDLIBS    += -lmpi
endif

#=============================================================================#

ifeq ($(SYSTEM), "NERUDA")
    CXX       = /home/eduardo/CLUES/libs/bin/mpic++
    LDLIBS    += -lmpi
endif

#=============================================================================#

ifeq ($(SYSTEM), "EREBOS")
    CXX       = mpic++
    LDLIBS    += -lmpi
endif


#=============================================================================#

ifeq ($(SYSTEM), "LEIBNIZ")
#    CXX       = /usr/lib64/mvapich2/bin/mpic++
#    CXX = /opt/intel-2017/compilers_and_libraries_2017.2.174/linux/mpi/intel64/bin/mpicxx
    CXX = mpicxx
    CXXFLAGS  += -w 
#    MPI_LIBS  += -L/opt/intel-2017/compilers_and_libraries_2017.2.174/linux/mpi/intel64/bin/mpicxx
#    MPI_LIBS  += -L/usr/lib64/mvapich2/lib/
#    MPI_INCL  += -I/usr/lib64/mvapich2/include/
#    LDLIBS    += -lmpich ${MPI_LIBS}
    LDLIBS    += -lmpi ${MPI_LIBS}
endif

#=============================================================================#
