#   METROC++: MErger TRees On C++, a scalable code for the computation of merger trees in cosmological simulations.
#   Copyright (C) Edoardo Carlesi 2018-2019
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

#   Makefile.config
#   System-specific compiler directives
#   Choose your system (or add your own):

#SYSTEM = "NERUDA"
#SYSTEM = "LAPTOP"
#SYSTEM = "BARBAGIANNI"
SYSTEM = "EREBOS"
#SYSTEM = "LEIBNIZ"

# Code options:

# If reading particles from the binary snapshot directly then allow to store more information (e.g. on X and V).
#OPT += -DPART_SNAPSHOT

# Print information (on all tasks) about memory allocation, communication and other boring stuff.
#OPT += -DVERBOSE

# Set the number of particle used at COMPILE TIME. The particles taken into account will go from 0 to NPTYPES-1
OPT += -DNPTYPES=2

# Enable Zoom Mode
#OPT += -DZOOM

# Disregard particle type, and use only particles ids. 
#OPT += -DNOPTYPE

	#=============================================================================#
	#			SYSTEM-SPECIFIC DIRECTIVES			      #
	#=============================================================================#

ifeq ($(SYSTEM), "LAPTOP")
    CXX       =  mpic++
    LDLIBS    += -lmpi
endif

#=============================================================================#

ifeq ($(SYSTEM), "BARBAGIANNI")
    CXX       =  mpic++
    LDLIBS    += -lmpi
endif

#=============================================================================#

ifeq ($(SYSTEM), "NERUDA")
    CXX       = /home/eduardo/CLUES/libs/bin/mpic++
    LDLIBS    += -lmpi
endif

#=============================================================================#

ifeq ($(SYSTEM), "EREBOS")
    CXX       = mpic++
    LDLIBS    += -lmpi
endif


#=============================================================================#

ifeq ($(SYSTEM), "LEIBNIZ")
    CXX = mpicxx
    CXXFLAGS  += -w 
    LDLIBS    += -lmpi ${MPI_LIBS}
endif

#=============================================================================#
