# Makefile.config
# Edoardo Carlesi 2018
# Choose your system (or add your own):

SYSTEM = "NERUDA"
#SYSTEM = "LAPTOP"
#SYSTEM = "BARBAGIANNI"
#SYSTEM = "EREBOS"

# Code options:

# If reading particles from the binary snapshot directly then allow to store more information (e.g. on X and V)
#OPT += -DPART_SNAPSHOT


#=============================================================================#

ifeq ($(SYSTEM), "LAPTOP")
    CXX       =  mpic++
#    MKLPATH   += /home/edoardo/devel/libs/
#    FFTW3PATH += /home/edoardo/devel/libs/lib/
#    OPT       += -DLINUX_LAPACK 
#    MPI_LIBS  += -L/usr/local/lib/
#    MPI_INCL  += -L/usr/local/include/
#    CXXFLAGS  += -I/usr/include 
#    CXXFLAGS  += -fopenmp -fpermissive
#    LDFLAGS   += -L/usr/lib64 -Wl,--no-as-needed 
#    LDLIBS    += -lreadline -lf2c -lgsl -lgslcblas -lfftw3 -lpthread -fPIC -lgfortran
endif

#=============================================================================#

ifeq ($(SYSTEM), "BARBAGIANNI")
    CXX       =  mpic++
    MKLPATH   += /home/edoardo/libs/
    FFTW3PATH += /home/edoardo/libs/
    OPT       += -DLINUX_LAPACK -D__FFTW3 -DNEW_FORMAT_WF
    MPI_LIBS  += -L/usr/local/lib/
    MPI_INCL  += -L/usr/local/include/
    CXXFLAGS  += -I/usr/include  -I$(FFTW3PATH)/include -I$(MKLPATH)/include -I$(MKLPATH)/include/fftw -I${MPI_INCL} ${OPT}
    CXXFLAGS   += -fopenmp -lfpermissive
    LDFLAGS   += -L/usr/lib64 -Wl,--no-as-needed -L$(FFTW3PATH)/lib ${MPI_LIBS}
    LDLIBS    += -lreadline -llapack_LINUX -lblas_LINUX -lf2c -lgsl -lgslcblas -lfftw3 -lpthread 
endif

#=============================================================================#

ifeq ($(SYSTEM), "NERUDA")
    CXX       = /home/eduardo/CLUES/libs/bin/mpic++
    MPI_LIBS  += -L/eduardo/CLUES/libs/lib/ 
    MPI_INCL  += -I/eduardo/CLUES/libs/include/
#    LDFLAGS   += -L/usr/lib64 -Wl,--no-as-needed ${MPI_LIBS}
#    LDFLAGS   += -L/usr/lib64 -Wl,--no-as-needed ${MPI_LIBS}
    LDLIBS    += -lmpi ${MPI_LIBS}
#    LDLIBS    += -lirc -limf -lreadline -lgsl -lfftw3 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lintlc -lmpi
endif

#=============================================================================#
ifeq ($(SYSTEM), "EREBOS")
    CXX       = mpic++
    MKLPATH   = /opt/soft/intel/compilers_and_libraries_2017.2.174/linux/mkl/
    FFTW3PATH = /z/carlesi/libs/
    GSLPATH = /z/carlesi/CLUES/ginnungagap/
    INTELPATH = /opt/soft/intel/compilers_and_libraries_2017.2.174/linux/mpi/intel64/
    MPIPATH  = ${INTELPATH}/../mpi/intel64
    OPT       += -DSCILINUX_MKL -D__FFTW3 
    CXXFLAGS  += -I/usr/include -I$(MKLPATH)/include -I$(FFTW3PATH)/include/fftw -I${MPIPATH}/include ${OPT} -I${GSLPATH}/include
    CXXFLAGS  += -fopenmp -fpermissive
    LDFLAGS   += -L/usr/lib64 -L$(MKLPATH)/lib/intel64_lin -Wl,--no-as-needed -L$(FFTW3PATH) -L${MPIPATH}/lib/ -L${INTELPATH}/lib/intel64_lin
    LDFLAGS   += -L${GSLPATH}/lib
    LDLIBS    += -lirc -limf -lreadline -lgsl -lfftw3 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lintlc -lmpi
endif

#=============================================================================#
